### ISSUE TITLE
Anyone else getting on sObject Employee when running the orgUnit.sh shell script

### ISSUE THREAD

**Issue by davidfekke** [forcedotcom/WorkDotCom-Partners#5]
I am getting the following error when I try to run the orgUnit.sh shell script to create the scratch Org;

Compiled successfully.
 ▸    ERROR: System.QueryException: sObject type 'Employee' is not
 ▸    supported.
 ▸    ERROR: AnonymousBlock: line 86, column 1
ERROR running force:apex:execute:  Execution failed.

Here is the log.

❯ ./orgInit.sh
Successfully created scratch org: 00D3D000000CF6PUAW, username: test-lnee4ekuvld7@example.com
Waiting for the package install request to complete. Status = IN_PROGRESS
Waiting for the package install request to complete. Status = IN_PROGRESS
Waiting for the package install request to complete. Status = IN_PROGRESS
Waiting for the package install request to complete. Status = IN_PROGRESS
Waiting for the package install request to complete. Status = IN_PROGRESS
Waiting for the package install request to complete. Status = IN_PROGRESS
Waiting for the package install request to complete. Status = IN_PROGRESS
Waiting for the package install request to complete. Status = IN_PROGRESS
Waiting for the package install request to complete. Status = IN_PROGRESS
Waiting for the package install request to complete. Status = IN_PROGRESS
Waiting for the package install request to complete. Status = IN_PROGRESS
Waiting for the package install request to complete. Status = IN_PROGRESS
Waiting for the package install request to complete. Status = IN_PROGRESS
Waiting for the package install request to complete. Status = IN_PROGRESS
Waiting for the package install request to complete. Status = IN_PROGRESS
Waiting for the package install request to complete. Status = IN_PROGRESS
Waiting for the package install request to complete. Status = IN_PROGRESS
Waiting for the package install request to complete. Status = IN_PROGRESS
Waiting for the package install request to complete. Status = IN_PROGRESS
Waiting for the package install request to complete. Status = IN_PROGRESS
Waiting for the package install request to complete. Status = IN_PROGRESS
Waiting for the package install request to complete. Status = IN_PROGRESS
Waiting for the package install request to complete. Status = IN_PROGRESS
Waiting for the package install request to complete. Status = IN_PROGRESS
Waiting for the package install request to complete. Status = IN_PROGRESS
Waiting for the package install request to complete. Status = IN_PROGRESS
Waiting for the package install request to complete. Status = IN_PROGRESS
Waiting for the package install request to complete. Status = IN_PROGRESS
Waiting for the package install request to complete. Status = IN_PROGRESS
Waiting for the package install request to complete. Status = IN_PROGRESS
Waiting for the package install request to complete. Status = IN_PROGRESS
Waiting for the package install request to complete. Status = IN_PROGRESS
Waiting for the package install request to complete. Status = IN_PROGRESS
Successfully installed package [04t5w000005dgkTAAQ]
Waiting for the package install request to complete. Status = IN_PROGRESS
Waiting for the package install request to complete. Status = IN_PROGRESS
Waiting for the package install request to complete. Status = IN_PROGRESS
Waiting for the package install request to complete. Status = IN_PROGRESS
Waiting for the package install request to complete. Status = IN_PROGRESS
Waiting for the package install request to complete. Status = IN_PROGRESS
Waiting for the package install request to complete. Status = IN_PROGRESS
Waiting for the package install request to complete. Status = IN_PROGRESS
Waiting for the package install request to complete. Status = IN_PROGRESS
Waiting for the package install request to complete. Status = IN_PROGRESS
Waiting for the package install request to complete. Status = IN_PROGRESS
Waiting for the package install request to complete. Status = IN_PROGRESS
Waiting for the package install request to complete. Status = IN_PROGRESS
Waiting for the package install request to complete. Status = IN_PROGRESS
Waiting for the package install request to complete. Status = IN_PROGRESS
Waiting for the package install request to complete. Status = IN_PROGRESS
Waiting for the package install request to complete. Status = IN_PROGRESS
Waiting for the package install request to complete. Status = IN_PROGRESS
Waiting for the package install request to complete. Status = IN_PROGRESS
Waiting for the package install request to complete. Status = IN_PROGRESS
Waiting for the package install request to complete. Status = IN_PROGRESS
Waiting for the package install request to complete. Status = IN_PROGRESS
Successfully installed package [04t5w000005dgkTAAQ]
Waiting for the package install request to complete. Status = IN_PROGRESS
Waiting for the package install request to complete. Status = IN_PROGRESS
Waiting for the package install request to complete. Status = IN_PROGRESS
Waiting for the package install request to complete. Status = IN_PROGRESS
Successfully installed package [04t5w000004Lpu3]
Waiting for the package install request to complete. Status = IN_PROGRESS
Waiting for the package install request to complete. Status = IN_PROGRESS
Waiting for the package install request to complete. Status = IN_PROGRESS
Waiting for the package install request to complete. Status = IN_PROGRESS
Waiting for the package install request to complete. Status = IN_PROGRESS
Waiting for the package install request to complete. Status = IN_PROGRESS
Waiting for the package install request to complete. Status = IN_PROGRESS
Successfully installed package [04t4S000000hXF3]
=== Pushed Source
STATE  FULL NAME                                                           TYPE               PROJECT PATH
─────  ──────────────────────────────────────────────────────────────────  ─────────────────  ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Add    wkcc__b2w_WorkplaceCommandCenter                                    CustomApplication  force-app/main/default/applications/wkcc__b2w_WorkplaceCommandCenter.app-meta.xml
Add    b2w_CommandCenterHome_Custom                                        FlexiPage          force-app/main/default/flexipages/b2w_CommandCenterHome_Custom.flexipage-meta.xml
Add    Command_Center_Appiphony_App_Admin                                  PermissionSet      force-app/main/default/permissionsets/Command_Center_Appiphony_App_Admin.permissionset-meta.xml
Add    Workplace_Command_Center_Location_Admin                             PermissionSet      force-app/main/default/permissionsets/Workplace_Command_Center_Location_Admin.permissionset-meta.xml
Add    Workplace_Command_Center_Standard_PermSet_Admin_Full_Access_Cloned  PermissionSet      force-app/main/default/permissionsets/Workplace_Command_Center_Standard_PermSet_Admin_Full_Access_Cloned.permissionset-meta.xml
Add    b2w_AdminAddOn                                                      PermissionSet      force-app/main/default/permissionsets/b2w_AdminAddOn.permissionset-meta.xml
Add    b2w_GlobalOperationsAddOn                                           PermissionSet      force-app/main/default/permissionsets/b2w_GlobalOperationsAddOn.permissionset-meta.xml
Add    b2w_GlobalOperationsExecutiveAddOn                                  PermissionSet      force-app/main/default/permissionsets/b2w_GlobalOperationsExecutiveAddOn.permissionset-meta.xml
Add    b2w_OperationsExecutiveAddOn                                        PermissionSet      force-app/main/default/permissionsets/b2w_OperationsExecutiveAddOn.permissionset-meta.xml
Add    b2w_Workplace_Command_Center_Access                                 PermissionSet      force-app/main/default/permissionsets/b2w_Workplace_Command_Center_Access.permissionset-meta.xml
Add    b2w_Workplace_Operations_Addon                                      PermissionSet      force-app/main/default/permissionsets/b2w_Workplace_Operations_Addon.permissionset-meta.xml
Add    Security                                                            Settings           force-app/main/default/settings/Security.settings-meta.xml
=== Permsets Assigned
USERNAME                       PERMISSION SET ASSIGNMENT
─────────────────────────────  ──────────────────────────────────────────────────────────────────
test-lnee4ekuvld7@example.com  Workplace_Command_Center_Standard_PermSet_Admin_Full_Access_Cloned
=== Permsets Assigned
USERNAME                       PERMISSION SET ASSIGNMENT
─────────────────────────────  ─────────────────────────
test-lnee4ekuvld7@example.com  b2w_Admin
=== Permsets Assigned
USERNAME                       PERMISSION SET ASSIGNMENT
─────────────────────────────  ─────────────────────────
test-lnee4ekuvld7@example.com  b2w_OperationsExecutive
=== Permsets Assigned
USERNAME                       PERMISSION SET ASSIGNMENT
─────────────────────────────  ─────────────────────────
test-lnee4ekuvld7@example.com  b2w_Operations
=== Permsets Assigned
USERNAME                       PERMISSION SET ASSIGNMENT
─────────────────────────────  ────────────────────────────
test-lnee4ekuvld7@example.com  b2w_OperationsExecutiveAddOn
=== Permsets Assigned
USERNAME                       PERMISSION SET ASSIGNMENT
─────────────────────────────  ──────────────────────────────
test-lnee4ekuvld7@example.com  b2w_Workplace_Operations_Addon
=== Permsets Assigned
USERNAME                       PERMISSION SET ASSIGNMENT
─────────────────────────────  ───────────────────────────────────
test-lnee4ekuvld7@example.com  b2w_Workplace_Command_Center_Access
=== Permsets Assigned
USERNAME                       PERMISSION SET ASSIGNMENT
─────────────────────────────  ─────────────────────────
test-lnee4ekuvld7@example.com  b2w_AdminAddOn
=== Permsets Assigned
USERNAME                       PERMISSION SET ASSIGNMENT
─────────────────────────────  ──────────────────────────────────
test-lnee4ekuvld7@example.com  b2w_GlobalOperationsExecutiveAddOn
=== Permsets Assigned
USERNAME                       PERMISSION SET ASSIGNMENT
─────────────────────────────  ─────────────────────────
test-lnee4ekuvld7@example.com  b2w_GlobalOperationsAddOn
=== Permsets Assigned
USERNAME                       PERMISSION SET ASSIGNMENT
─────────────────────────────  ───────────────────────────────────────
test-lnee4ekuvld7@example.com  Workplace_Command_Center_Location_Admin
=== Permsets Assigned
USERNAME                       PERMISSION SET ASSIGNMENT
─────────────────────────────  ──────────────────────────────────
test-lnee4ekuvld7@example.com  Command_Center_Appiphony_App_Admin
ERROR running force:data:tree:import:  The requested resource does not exist
Compiled successfully.
Executed successfully.

47.0 APEX_CODE,DEBUG;APEX_PROFILING,INFO
Execute Anonymous: // Updates Location#VisitorAddressId using Address records
Execute Anonymous: // This apex iterates across all addresses and locations
Execute Anonymous: // updating Location#VisitorAddressId with the Address#Id
Execute Anonymous: // when an Address#ParentId is equal to a Location#Id
Execute Anonymous:
Execute Anonymous: List<SObject> addresses = database.query('select id, parentId from Address');
Execute Anonymous: List<SObject> locations = database.query('select id, visitoraddressid from Location');
Execute Anonymous:
Execute Anonymous: for (Sobject location : locations) {
Execute Anonymous:     for (SObject address : addresses) {
Execute Anonymous:         Object parentId = address.get('ParentId');
Execute Anonymous:         if (parentId == location.get('Id')) {
Execute Anonymous:             location.put('VisitorAddressId', address.get('Id'));
Execute Anonymous:         }
Execute Anonymous:     }
Execute Anonymous: }
Execute Anonymous:
Execute Anonymous: upsert locations;
13:57:58.16 (16989236)|USER_INFO|[EXTERNAL]|0053D000004Kg2W|test-lnee4ekuvld7@example.com|(GMT-07:00) Pacific Daylight Time (America/Los_Angeles)|GMT-07:00
13:57:58.16 (17012992)|EXECUTION_STARTED
13:57:58.16 (17020162)|CODE_UNIT_STARTED|[EXTERNAL]|execute_anonymous_apex
13:57:58.496 (496743483)|CUMULATIVE_LIMIT_USAGE
13:57:58.496 (496743483)|LIMIT_USAGE_FOR_NS|(default)|
  Number of SOQL queries: 2 out of 100
  Number of query rows: 145 out of 50000
  Number of SOSL queries: 0 out of 20
  Number of DML statements: 1 out of 150
  Number of DML rows: 135 out of 10000
  Maximum CPU time: 169 out of 10000
  Maximum heap size: 0 out of 6000000
  Number of callouts: 0 out of 100
  Number of Email Invocations: 0 out of 10
  Number of future calls: 0 out of 50
  Number of queueable jobs added to the queue: 0 out of 50
  Number of Mobile Apex push calls: 0 out of 10

13:57:58.496 (496743483)|CUMULATIVE_LIMIT_USAGE_END

13:57:58.16 (500501116)|CODE_UNIT_STARTED|[EXTERNAL]|01q3D000000VwW7|wdcLocation on Location trigger event AfterUpdate|__sfdc_trigger/wdcLocation
13:57:58.16 (822403557)|CODE_UNIT_STARTED|[EXTERNAL]|01q3D000000VwW5|floor on Floor trigger event AfterInsert|__sfdc_trigger/floor
13:57:58.869 (869099324)|CUMULATIVE_LIMIT_USAGE
13:57:58.869 (869099324)|LIMIT_USAGE_FOR_NS|(default)|
  Number of SOQL queries: 6 out of 100
  Number of query rows: 192 out of 50000
  Number of SOSL queries: 0 out of 20
  Number of DML statements: 2 out of 150
  Number of DML rows: 254 out of 10000
  Maximum CPU time: 387 out of 10000
  Maximum heap size: 0 out of 6000000
  Number of callouts: 0 out of 100
  Number of Email Invocations: 0 out of 10
  Number of future calls: 0 out of 50
  Number of queueable jobs added to the queue: 0 out of 50
  Number of Mobile Apex push calls: 0 out of 10

13:57:58.869 (869099324)|CUMULATIVE_LIMIT_USAGE_END

13:57:58.16 (870545856)|CODE_UNIT_FINISHED|floor on Floor trigger event AfterInsert|__sfdc_trigger/floor
13:57:58.16 (893907589)|CODE_UNIT_STARTED|[EXTERNAL]|01q3D000000VwW3|building on Building trigger event AfterUpdate|__sfdc_trigger/building
13:57:58.914 (914757024)|CUMULATIVE_LIMIT_USAGE
13:57:58.914 (914757024)|LIMIT_USAGE_FOR_NS|(default)|
  Number of SOQL queries: 7 out of 100
  Number of query rows: 199 out of 50000
  Number of SOSL queries: 0 out of 20
  Number of DML statements: 2 out of 150
  Number of DML rows: 254 out of 10000
  Maximum CPU time: 387 out of 10000
  Maximum heap size: 0 out of 6000000
  Number of callouts: 0 out of 100
  Number of Email Invocations: 0 out of 10
  Number of future calls: 0 out of 50
  Number of queueable jobs added to the queue: 0 out of 50
  Number of Mobile Apex push calls: 0 out of 10

13:57:58.914 (914757024)|CUMULATIVE_LIMIT_USAGE_END

13:57:58.16 (916093547)|CODE_UNIT_FINISHED|building on Building trigger event AfterUpdate|__sfdc_trigger/building
13:57:58.16 (942840385)|EXCEPTION_THROWN|[145]|System.DmlException: Upsert failed. First exception on row 0; first error: REQUIRED_FIELD_MISSING, Required fields are missing: [wdctest__Building__c]: [wdctest__Building__c]
13:57:58.16 (945004457)|USER_DEBUG|[147]|DEBUG|******* message: Upsert failed. First exception on row 0; first error: REQUIRED_FIELD_MISSING, Required fields are missing: [wdctest__Building__c]: [wdctest__Building__c]
13:57:58.16 (945050296)|USER_DEBUG|[148]|DEBUG|******* stack: Trigger.wdcLocation: line 145, column 1
13:57:58.945 (945067590)|CUMULATIVE_LIMIT_USAGE
13:57:58.945 (945067590)|LIMIT_USAGE_FOR_NS|(default)|
  Number of SOQL queries: 5 out of 100
  Number of query rows: 171 out of 50000
  Number of SOSL queries: 0 out of 20
  Number of DML statements: 2 out of 150
  Number of DML rows: 254 out of 10000
  Maximum CPU time: 169 out of 10000
  Maximum heap size: 0 out of 6000000
  Number of callouts: 0 out of 100
  Number of Email Invocations: 0 out of 10
  Number of future calls: 0 out of 50
  Number of queueable jobs added to the queue: 0 out of 50
  Number of Mobile Apex push calls: 0 out of 10

13:57:58.945 (945067590)|CUMULATIVE_LIMIT_USAGE_END

13:57:58.16 (946413611)|CODE_UNIT_FINISHED|wdcLocation on Location trigger event AfterUpdate|__sfdc_trigger/wdcLocation
13:57:58.992 (992992031)|CUMULATIVE_LIMIT_USAGE
13:57:58.992 (992992031)|LIMIT_USAGE_FOR_NS|(default)|
  Number of SOQL queries: 5 out of 100
  Number of query rows: 171 out of 50000
  Number of SOSL queries: 0 out of 20
  Number of DML statements: 2 out of 150
  Number of DML rows: 254 out of 10000
  Maximum CPU time: 169 out of 10000
  Maximum heap size: 0 out of 6000000
  Number of callouts: 0 out of 100
  Number of Email Invocations: 0 out of 10
  Number of future calls: 0 out of 50
  Number of queueable jobs added to the queue: 0 out of 50
  Number of Mobile Apex push calls: 0 out of 10

13:57:58.992 (992992031)|CUMULATIVE_LIMIT_USAGE_END

13:57:58.16 (993037783)|CODE_UNIT_FINISHED|execute_anonymous_apex
13:57:58.16 (993052370)|EXECUTION_FINISHED

Compiled successfully.
 ▸    ERROR: System.QueryException: sObject type 'Employee' is not
 ▸    supported.
 ▸    ERROR: AnonymousBlock: line 86, column 1
ERROR running force:apex:execute:  Execution failed.

Compiled successfully.
Executed successfully.

47.0 APEX_CODE,DEBUG;APEX_PROFILING,INFO
Execute Anonymous:
Execute Anonymous: //Reset the default admin user password because Scratch orgs don't supply password to be able to login directly
Execute Anonymous: User u = [select id,name, LastName, FirstName, username, ProfileId,  alias, email, TimeZoneSidKey, LanguageLocaleKey, EmailEncodingKey, LocaleSidKey
Execute Anonymous:           from User where IsActive=true and Profile.Name='System Administrator' limit 1];
Execute Anonymous: //Email user on password reset so they have the link to login again in case they close their browser.
Execute Anonymous: System.resetPassword (u.Id, true);
13:58:08.19 (19268645)|USER_INFO|[EXTERNAL]|0053D000004Kg2W|test-lnee4ekuvld7@example.com|(GMT-07:00) Pacific Daylight Time (America/Los_Angeles)|GMT-07:00
13:58:08.19 (19296723)|EXECUTION_STARTED
13:58:08.19 (19301814)|CODE_UNIT_STARTED|[EXTERNAL]|execute_anonymous_apex
13:58:08.153 (153422731)|CUMULATIVE_LIMIT_USAGE
13:58:08.153 (153422731)|LIMIT_USAGE_FOR_NS|(default)|
  Number of SOQL queries: 1 out of 100
  Number of query rows: 1 out of 50000
  Number of SOSL queries: 0 out of 20
  Number of DML statements: 1 out of 150
  Number of DML rows: 1 out of 10000
  Maximum CPU time: 0 out of 10000
  Maximum heap size: 0 out of 6000000
  Number of callouts: 0 out of 100
  Number of Email Invocations: 0 out of 10
  Number of future calls: 0 out of 50
  Number of queueable jobs added to the queue: 0 out of 50
  Number of Mobile Apex push calls: 0 out of 10

13:58:08.153 (153422731)|CUMULATIVE_LIMIT_USAGE_END

13:58:08.19 (153473427)|CODE_UNIT_FINISHED|execute_anonymous_apex
13:58:08.19 (153489502)|EXECUTION_FINISHED

Access org 00D3D000000GSFUAW as user test-user@sample.com with the following URL: https://page-customization-4603.cs99.my.salesforce.com/secur/frontdoor.jsp?sid=7897fsd897f89sd789f07s8d907f890s78f90sd890dsfsfdfdsvvfsfs

**Comment by jrattanpal** [comment]
Hi,

It seems related to Appiphony sample app in the Work.com repo. We are looking into it. 

But rest of the Work.com should still work.

**Comment by davidfekke** [comment]
Thanks. I was able to use the help page to create scratch org with the work.com packages, but it was very time consuming.
